### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by isaacdunyo** [alexweissman/UserFrosting-OAuth#4]
This is from the error log. Any help please?

PHP Fatal error: Class 'League\OAuth2\Client\Provider\Facebook' not found in /home/************/public_html/users/plugins/UserFrosting-OAuth/controllers/OAuthControllerFacebook.php on line 28 

Thanks

**Comment by frostbitten** [comment]
did you run composer update when you set up the plugin?

**Comment by isaacdunyo** [comment]
After updating, looked in error log: failed opening config-plugin.php - 

PHP Warning:  require_once(C:\xampp2\htdocs*****_\users/plugins/UserFrosting-OAuth/config-plugin.php): failed to open stream: No such file or directory in C:\xampp2\htdocs\**_***\users\initialize.php on line 278

[29-Dec-2015 13:23:41 America/New_York] PHP Fatal error:  require_once(): Failed opening required 'C:\xampp2\htdocs*****_\users/plugins/UserFrosting-OAuth/config-plugin.php' (include_path='.;C:\xampp2\php\PEAR') in C:\xampp2\htdocs\**_***\users\initialize.php on line 278

**Comment by frostbitten** [comment]
Is the plugin directory named correctly? That is, can you navigate to "/plugins/UserFrosting-OAuth/" from that "users" directory from your operating system's file explorer?

**Comment by isaacdunyo** [comment]
Yes it is. And ever since I updated composer, tried logging into the dashboard and I get a server 500 error. with the League\OAuth2\Client\Provider\Facebook class not found error in php logs. :-(

**Comment by isaacdunyo** [comment]
Is it weird I keep getting different issues each time another is fixed?

users\models\auth\AccessConditionExpression.php on line 48: Cannot instantiate interface PhpParser\Parser

maybe an issue with my composer install? it says the .git directory is missing.

**Comment by frostbitten** [comment]
Just want to make sure, do you have the latest version of the plugin downloaded? Best way to be sure is to check OAuthControllerFacebook.php to see if there is a variable called "$graphApiVersion". If that's there, you have the correct version.

**Comment by isaacdunyo** [comment]
Yes it is, I can confirm i have the variable called "$graphApiVersion".

**Comment by frostbitten** [comment]
Okay. Just wondering, are the **\* something you edited out of the error? If so, and your error contains the full path to the file, try copying that full path (including filename) and pasting it into the location bar of any explorer window. Hit enter. If you get an error, your file does not exist where you think it does. if it does exist, it should open up in whatever the default application is for your php files. Let me know your result

**Comment by githubsrinath** [comment]
Hi,

I am struggling with same error in my website.

I was waiting for continuity of this bug fix.  since it took longer time to respond.  ... i thought let me provide more inputs to get this thing fixed.

Here are my details:

1. I have arvixe apache, Linux server
2. Installed Userfrosting successfully... Tested works fine.
3. Downloaded UserFrosting-OAuth zip and installed in plugin folder.
4. Updated UserFrosting-OAuth/controllers/OAuthControllerFacebook.php

   Update following 3 lines, values taken from Facebook App creation Dashboard 
   $clientId = '173309793023XXXX';
   $clientSecret = 'bdb1a9e2cb1ab8898776c35edXXXXXXX';
   $graphApiVersion = 'v2.5'; // probably "v2.0"

5. Added composer.json in the userfrosting directory

 ```
   "league/oauth2-facebook": "*",
    "league/oauth2-linkedin":"*",
    "league/oauth2-google":"*",
    "league/oauth2-instagram":"*",
```
    in begining of composer.json 

     and ran  command 
   $>  composer update

6. Now calling the following command from URL 
    http://mywebsite.com/oauth/facebook/login

7.  I get error : Server 500  

8 My Server error log says : 

```
[07-Mar-2016 00:48:00 America/New_York] PHP Fatal error:  Class 'League\OAuth2\Client\Provider\Facebook' not found in /home/jalsa/public_html/uf/userfrosting/plugins/UserFrosting-OAuth/controllers/OAuthControllerFacebook.php on line 29
[07-Mar-2016 00:48:00 America/New_York] Fatal error (1) in /home/jalsa/public_html/uf/userfrosting/plugins/UserFrosting-OAuth/controllers/OAuthControllerFacebook.php on line 29: Class 'League\OAuth2\Client\Provider\Facebook' not found
```



 Did i miss anything?  Please help me.  

Many Thanks Srinath

**Comment by isaacdunyo** [comment]
Quick update: Reinstalled application and updated composer and that fixed the issue.
